spring.application.name=e-commerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tiger
#Create - used to create tables each time when applications runs
spring.jpa.hibernate.ddl-auto=update
#to see which is getting executed we use this below line
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

spring.jpa.properties.hibernate.format_sql=true